In [ ]:
# Pandas Data Science Library
import numpy as np
import pandas as pd
print(pd.__version__)

2.2.2

In [ ]:
# numpy --> array()
arr = np.array([10,20,30,40,50])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50]

In [ ]:
# Pandas Series
# Series is 1D Labelled Array

s = pd.Series([10,20,30,40,50])
print(type(s))
print(s)
print(s.shape)

# In Numpy --> Only Numbers
# In Series --> Numbers + Labels (index)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
4    50
dtype: int64
(5,)

In [ ]:
info = pd.Series(['John',28,6700,'Klang'],index=['name','Age','sal','city'])
print(info)
print(info['name'])   # indexing
print(info['Age'])    # getting data values using get()
print(info.iloc[0])   # iloc --> index locatiom

# Series ia like a Dictionary + array combo

name     John
Age        28
sal      6700
city    Klang
dtype: object
John
28
John

In [ ]:
# values property
# print only values

print(info.values)

['John' 28 6700 'Klang']

In [ ]:
import pandas as pd

# Indexing Slicing and Using for Loop
s = pd.Series([100,200,300,400,500,600],index=['v1','v2','v3','v4','v5','v6'])
print(s)

# 100  200  300  400  500  600
#  0    1    2    3    4    5
# -6   -5   -4   -3   -2   -1
# v1   v2   v3   v4   v5   v6

# Indexing in Series can be done by using [] or iloc[] or loc[]
print('\nIndexing in Series')
print(s.iloc[0])    # for index numbers
print(s.loc['v5'])  # loc used for Labels
print(s['v2'])      # [] used for Labels
print(s.iloc[-1])

print('\nSlicing in Series')
print(s[1:4])          # 4 will be excluded --> stopIndex
print(s['v1' : 'v5']) # if performing slicing using Labels, the end Label is included

# 100  400  600
print('\nFor Specific Information')
print(s[['v1','v4','v6']])  # for specific information s[['','','']]
print(s[['v1','v2','v3']].values)

# conditional selection
print('\nconditional selection')
print(s[s%3==0])

v1    100
v2    200
v3    300
v4    400
v5    500
v6    600
dtype: int64

Indexing in Series
100
500
200
600

Slicing in Series
v2    200
v3    300
v4    400
dtype: int64
v1    100
v2    200
v3    300
v4    400
v5    500
dtype: int64

For Specific Information
v1    100
v4    400
v6    600
dtype: int64
[100 200 300]

conditional selection
v3    300
v6    600
dtype: int64

In [ ]:
# Using for Loop
for i in s:
  print(i)

100
200
300
400
500
600

In [ ]:
for k,v in s.items():
  print(k,v)

v1 100
v2 200
v3 300
v4 400
v5 500
v6 600

In [ ]:
for i in enumerate(s):
  print(i)

(0, 100)
(1, 200)
(2, 300)
(3, 400)
(4, 500)
(5, 600)

In [ ]:
# Pandas DataFrame
# it is used to display the information in a tabular fashion
# Pandas DataFrame is 2D Array

data = {
    'name':['John','Alex','Smith'],
    'dept':['IT','HR','MR'],
    'sal':[6700,5600,600],
    'city':['KL','JB','ML']
}
print(data)

{'name': ['John', 'Alex', 'Smith'], 'dept': ['IT', 'HR', 'MR'], 'sal': [6700, 5600, 600], 'city': ['KL', 'JB', 'ML']}

In [ ]:
df = pd.DataFrame(data)
print(df)

# OR

df = pd.DataFrame(data)
df

    name dept   sal city
0   John   IT  6700   KL
1   Alex   HR  5600   JB
2  Smith   MR   600   ML

    name dept   sal city
0   John   IT  6700   KL
1   Alex   HR  5600   JB
2  Smith   MR   600   ML

In [ ]:
print(df.shape)

(3, 4)

In [ ]:
data = {
    'Calories':[420,380,560],
    'Duration':[56,30,75]
}
df = pd.DataFrame(data,index=['day1','day2','day3'])
df

      Calories  Duration
day1       420        56
day2       380        30
day3       560        75

In [ ]:
df['Calories']

day1    420
day2    380
day3    560
Name: Calories, dtype: int64

In [ ]:
print(df['Calories'].values)

[420 380 560]

In [ ]:
df.loc['day1']

Calories    420
Duration     56
Name: day1, dtype: int64

In [ ]:
df.loc[['day1','day3']]

      Calories  Duration
day1       420        56
day3       560        75